// Build config for this project. You don't need to edit it.
plugins {
    id 'java'
    id 'application'
}

java {
    // WPILib 2026 and the team's robot code use Java 17, so we do too.
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

application {
    mainClass = 'rankup.Main'
}

repositories {
    mavenCentral()
}
