package frc.robot.sim;

import static edu.wpi.first.units.Units.Rotations;
import static edu.wpi.first.units.Units.RotationsPerSecond;

import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.sim.TalonFXSimState;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.util.Units;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.SingleJointedArmSim;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.smartdashboard.Mechanism2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismLigament2d;
import edu.wpi.first.wpilibj.smartdashboard.MechanismRoot2d;
import edu.wpi.first.wpilibj.util.Color;
import edu.wpi.first.wpilibj.util.Color8Bit;

// ============================================================
// RANK:        Robot Emerald: Arm to Presets
// FILE:        sim/ArmSimHelper.java
// STEPS HERE:  none — THIS FILE IS NOT PART OF THE ASSESSMENT
// GUIDE:       GUIDE_URL  (section "Robot Emerald")
// RUN:         ./gradlew simulateJava    CHECK: ./gradlew rankCheck
// PASSES WHEN: (not assessed)
// ============================================================
//
// DO NOT EDIT THIS FILE.
//
// This is a physics simulation of a real arm — gravity, inertia, hard stops — plus the
// drawing of it you see on SmartDashboard. It is finished for you, because simulating an arm
// is not what Emerald is about. Tuning one is.
//
// ------------------------------------------------------------
//  THE PHYSICAL FACTS OF THIS ARM
//
//  These describe the pretend hardware. They are not answers to any step — they are the
//  equivalent of reading a number off a real gearbox. Put the gear ratio in your Constants
//  so your code and this simulation agree:
//
//      GEAR RATIO:   50:1   (50 motor rotations per 1 rotation of the arm)
//      ARM LENGTH:   0.80 m
//      ARM MASS:     4.0 kg
//      HARD STOPS:   -10 degrees to 110 degrees
//      ZERO DEGREES: arm horizontal, pointing forward. Positive is upward.
//
//  If your Constants disagree with these, your arm will behave strangely in simulation and
//  you will spend an evening tuning a number that was never the problem.
// ------------------------------------------------------------

public class ArmSimHelper {

    /** 50 motor rotations per arm rotation. Mirror this in your Constants. */
    public static final double GEAR_RATIO = 50.0;

    private static final double ARM_LENGTH_METRES = 0.80;
    private static final double ARM_MASS_KG = 4.0;
    private static final double MIN_ANGLE_DEGREES = -10.0;
    private static final double MAX_ANGLE_DEGREES = 110.0;
    private static final double LOOP_PERIOD_SECONDS = 0.020;

    /** How long the drawn arm is on the dashboard, in the Mechanism2d's own units. */
    private static final double DRAWN_LENGTH = 24.0;

    private final SingleJointedArmSim armSim;
    private final MechanismLigament2d armLigament;
    private final MechanismLigament2d setpointLigament;

    public ArmSimHelper() {
        DCMotor gearbox = DCMotor.getKrakenX60(1);

        armSim = new SingleJointedArmSim(
                gearbox,
                GEAR_RATIO,
                SingleJointedArmSim.estimateMOI(ARM_LENGTH_METRES, ARM_MASS_KG),
                ARM_LENGTH_METRES,
                Units.degreesToRadians(MIN_ANGLE_DEGREES),
                Units.degreesToRadians(MAX_ANGLE_DEGREES),
                true, // simulate gravity — this is the whole reason you need a kG term
                Units.degreesToRadians(MIN_ANGLE_DEGREES));

        // A little stick-figure of the arm, so you can watch it move instead of reading
        // numbers. It shows up on SmartDashboard under "Arm".
        Mechanism2d mechanism = new Mechanism2d(60, 60);
        MechanismRoot2d pivot = mechanism.getRoot("ArmPivot", 30, 30);

        setpointLigament = pivot.append(new MechanismLigament2d(
                "Setpoint", DRAWN_LENGTH, MIN_ANGLE_DEGREES, 4, new Color8Bit(Color.kOrange)));
        armLigament = pivot.append(new MechanismLigament2d(
                "Arm", DRAWN_LENGTH, MIN_ANGLE_DEGREES, 8, new Color8Bit(Color.kCyan)));

        SmartDashboard.putData("Arm", mechanism);
    }

    /**
     * Steps the physics forward one robot loop and writes the result into the motor's
     * simulated encoder. Call this from simulationPeriodic().
     */
    public void update(TalonFX motor) {
        TalonFXSimState simState = motor.getSimState();

        simState.setSupplyVoltage(RobotController.getBatteryVoltage());

        armSim.setInputVoltage(simState.getMotorVoltage());
        armSim.update(LOOP_PERIOD_SECONDS);

        // The rotor turns GEAR_RATIO times for every turn of the arm.
        double armRotations = Units.radiansToRotations(armSim.getAngleRads());
        double armRotationsPerSecond = Units.radiansToRotations(armSim.getVelocityRadPerSec());

        simState.setRawRotorPosition(Rotations.of(armRotations * GEAR_RATIO));
        simState.setRotorVelocity(RotationsPerSecond.of(armRotationsPerSecond * GEAR_RATIO));

        armLigament.setAngle(Units.radiansToDegrees(armSim.getAngleRads()));
    }

    /** Draws where you asked the arm to go, next to where it actually is. */
    public void setSetpointForDisplay(double degrees) {
        setpointLigament.setAngle(degrees);
    }

    /** The real angle of the simulated arm, in degrees. Handy for sanity checks. */
    public double getActualAngleDegrees() {
        return Units.radiansToDegrees(armSim.getAngleRads());
    }
}
