package frc.robot.sim;

import static edu.wpi.first.units.Units.RotationsPerSecond;
import static edu.wpi.first.units.Units.Rotations;

import com.ctre.phoenix6.hardware.TalonFX;
import com.ctre.phoenix6.sim.TalonFXSimState;
import edu.wpi.first.math.system.plant.DCMotor;
import edu.wpi.first.math.system.plant.LinearSystemId;
import edu.wpi.first.wpilibj.RobotController;
import edu.wpi.first.wpilibj.simulation.DCMotorSim;

// ============================================================
// RANK:        Robot Diamond: Simple Motor Subsystem
// FILE:        sim/MotorSimHelper.java
// STEPS HERE:  none — THIS FILE IS NOT PART OF THE ASSESSMENT
// GUIDE:       GUIDE_URL  (section "Robot Diamond")
// RUN:         ./gradlew simulateJava    CHECK: ./gradlew rankCheck
// PASSES WHEN: (not assessed)
// ============================================================
//
// DO NOT EDIT THIS FILE.
//
// This is plumbing, already finished for you. Physics simulation is not what Diamond is
// about, and writing it yourself would take longer than the rest of the rank.
//
// What it does: a real TalonFX has an encoder that moves when the motor turns. In
// simulation nothing physically turns, so the encoder would read zero forever and you could
// never test your code. This class fakes the physics — it reads the voltage your code is
// commanding, works out how fast a real motor would be spinning, and writes that back into
// the TalonFX's simulated encoder.
//
// You use it from simulationPeriodic() in Robot.java (step 10). That is the only thing you
// need to know about it.

public class MotorSimHelper {

    /** The robot loop runs every 20 milliseconds. */
    private static final double LOOP_PERIOD_SECONDS = 0.020;

    private final DCMotorSim motorSim;
    private final double gearing;

    /**
     * @param gearing how many motor rotations make one output rotation (a 10:1 gearbox is 10.0)
     * @param momentOfInertiaKgMetresSquared how hard the thing is to spin up; 0.001 is a light
     *     roller, 0.05 is something chunky
     */
    public MotorSimHelper(double gearing, double momentOfInertiaKgMetresSquared) {
        this.gearing = gearing;
        DCMotor gearbox = DCMotor.getKrakenX60(1);
        this.motorSim = new DCMotorSim(
                LinearSystemId.createDCMotorSystem(gearbox, momentOfInertiaKgMetresSquared, gearing),
                gearbox);
    }

    /**
     * Steps the fake physics forward one robot loop and writes the result back into the
     * motor's simulated encoder. Call this from simulationPeriodic().
     */
    public void update(TalonFX motor) {
        TalonFXSimState simState = motor.getSimState();

        // Tell the simulated motor controller what the battery is doing.
        simState.setSupplyVoltage(RobotController.getBatteryVoltage());

        // Read the voltage your code is commanding, and push it through the physics model.
        motorSim.setInputVoltage(simState.getMotorVoltage());
        motorSim.update(LOOP_PERIOD_SECONDS);

        // Write the result back as ROTOR movement. The rotor spins `gearing` times for every
        // turn of the output shaft, which is why both numbers are multiplied by it.
        simState.setRawRotorPosition(
                Rotations.of(motorSim.getAngularPositionRotations() * gearing));
        simState.setRotorVelocity(
                RotationsPerSecond.of(motorSim.getAngularVelocityRPM() / 60.0 * gearing));
    }
}
